### ISSUE TITLE
Unable to generate arm image for bumping Alpine to 3.14.2

### ISSUE THREAD

**Issue by basvanbeek** [openzipkin/docker-alpine#14]
While trying to bump the Alpine version we get the following error in the `deploy` action:

https://github.com/openzipkin/docker-alpine/runs/3504114570

**Comment by llinder** [comment]
I'm no expert on multi-arch builds but this might be [related to Docker changes](https://github.com/docker/for-linux/issues/1170). I can replicate this locally on MacOS and I can also work around it by using `buildx`. Looking deeper I see some [comments here](https://github.com/openzipkin/docker-alpine/blob/master/build-bin/docker/docker_build#L22) about not using `buildx` however when I set `DOCKER_BUILDKIT=1` the build succeeds. I suppose the Docker Hub quota might still be an issue but maybe its worth trying to use `buildx` anyway? For all I know there isn't another fix but maybe someone else has experience and can share some ideas.

**Comment by llinder** [comment]
Checked that arm64 is published now. Going to close this and start working on releasing new zipkin images.
